version: '3'
services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql-notebook
    restart: "no"
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=notebook_db
      - MYSQL_USER=note
      - MYSQL_PASSWORD=note
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - "3308:3306"
    networks:
      - notebook-network
